apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-contacts
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-headers: 'Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,Accept-Language'
    nginx.ingress.kubernetes.io/cors-max-age: '600'
    nginx.ingress.kubernetes.io/proxy-body-size: '12m'
    nginx.ingress.kubernetes.io/rewrite-target: '/contacts/$2'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - 52.157.249.30.nip.io
      secretName: tls-secret
  rules:
    - host: 52.157.249.30.nip.io
      http:
        paths:
          - path: /api/contacts(\/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: contactsapi
                port:
                  number: 8080